# Generated by Django 4.2.4 on 2023-09-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urinetest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedimage",
            name="upload_datetime",
        ),
    ]
